title: Hello, world! I'm Zehao (Zach) Guan.
description: > # this means to ignore newlines until "baseurl:"
  I am a first-year graduate student pursuing my Master degree in the MSAII program. I have hands-on experience on software development and implementing AI techniques to solve practical projects.
permalink: ':title/'
baseurl: "zach96guan.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: GuanZach96 #if your site has a twitter account, enter it here

# Author Settings
author: Zehao Guan
author-img: david-freeman.jpg
about-author: Life should not be a journey to the grave.
social-twitter: GuanZach96
social-facebook: zach96guan
#social-instagram: zach96guan
social-github: zach96guan
social-linkedin: zach-guan
social-email: zehaog@cs.cmu.edu

# Disqus
discus-identifier: zehaoguan # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
